### ISSUE TITLE
Option to turn off location information

### ISSUE THREAD

**Issue by jaens** [syntax-tree/unist-util-inspect#10]
The README.md indicates that the tree is printed out in quite a clean way, but in reality, a lot of location information is added:

```
text: "[" (9:144-9:146, 278-280)
```

It would be nice to have an option to skip the printing of location information, as it clutters up the display significantly and is only useful in very specific debugging situations.

**Comment by wooorm** [comment]
Can you provide more on why? https://raw.githubusercontent.com/syntax-tree/.github/master/.github/ISSUE_TEMPLATE/2-feature.md

**Comment by jaens** [comment]
I think the main reason is what I already said - the numbers take up more space than the actual content and make it hard to read / scan (I assume reading it is the main use case, specifically the structure of the tree, not the miscellanea like the exact locations of the nodes).

**Comment by wooorm** [comment]
> miscellanea like the exact locations of the nodes

In my opinion positional information is one of the greatest parts of unified. I often use this utility to quickly see those too.

If you’re not interested in positional information, would [`unist-util-remove-position`](https://github.com/syntax-tree/unist-util-remove-position) work for your use case?

**Comment by jaens** [comment]
Whether seeing it is useful depends on which part of the pipeline you are working on - when doing tokenizers / parsers, of course it would be useful.

On the other hand, since I am (currently) working on processors that take chunks of nodes as input, there's no use for me knowing *where* those nodes are, rather it's all about the structure.

Yes, unist-util-remove-position would work, but it mutates the tree so it's not suitable as-is for debugging. Is there a suggested util to copy the tree?

**Comment by wooorm** [comment]
Released in 6.0.0!
