### ISSUE TITLE
Display value for node with children as for node without children

### ISSUE THREAD

**Issue by florent-andre** [syntax-tree/unist-util-inspect#15]
### Subject of the feature

Have the same `node.value` display for nodes with children and nodes without.

### Problem

* It's easy to ask this question on the keyboard : "Why I have value display for some of my nodes and not for others ?"
* Value is an interesting information for any node with children or not

### Expected behaviour

* actual behaviour : 
![image](https://user-images.githubusercontent.com/837462/83861129-80357300-a720-11ea-96dc-188138174d99.png)

* expected for `withChildrenNode[1]` => `withChildrenNode[1] "wCN value"`

* related show code : 
```js
const noCN = { type: 'noChildrenNode', value: 'nCN value'}
const wCN = { type: 'withChildrenNode', value: 'wCN value', children: [{type:'message', value: 'wCN `value` no display'}]}
const root = { type: 'root', children: [noCN, wCN]}
console.log(inspect(root))
```

### Alternatives

* a configuration for .value display strategy ?

**Comment by wooorm** [comment]
Why do you have nodes with both a `.value` and `.children`?

**Comment by florent-andre** [comment]
`.value` is the content of the parent node and `.children` contains nodes related to the parent.  
`.children` are part of the parent's, but not it's only "value". (Like in family :)  )
It may be a personal misconception of the way it should work in unist.

**Comment by ChristianMurphy** [comment]
@florent-andre what I think @wooorm is getting at is `Literal`'s https://github.com/syntax-tree/unist#literal have values, `Parent`s have `children` https://github.com/syntax-tree/unist#parent
[`mdast`](https://github.com/syntax-tree/mdast), [`hast`](https://github.com/syntax-tree/hast), and [`nlcst`](https://github.com/syntax-tree/nlcst) nodes will extend one or the other, never both.

Having nodes which have both `value` and `children` creates some ambiguity on what the content of the node really is.

**Comment by florent-andre** [comment]
Okay ! I got it ! it totally make sense now. 
I now have to see now how my tree growth regarding this ! ;) 
Sorry for my disturbance, and thanks a lot for your answers, your time, and for this great ecosystem of cool libs ! 
regards.

**Comment by wooorm** [comment]
Cool!

I’d be interested in hearing what you’re up to!
