### ISSUE TITLE
Typings

### ISSUE THREAD

**Issue by shanehandley** [syntax-tree/unist-util-inspect#8]
### Subject of the feature

Request: Typescript .d.ts typings

### Problem

Not urgent. But typings would be useful. I have since mocked them to get by.

### Alternatives

I have checked the typings on DefinitelyTyped for [unist-util-is](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/95a4800caa5b80801f02ddf400e03698b9747042/types/unist-util-is/index.d.ts) and tried to adapt them to this module. But creating typings is not my strong point.

Thank you for your work.

**Comment by wooorm** [comment]
PRs welcome! @ChristianMurphy and @Rokt33r can help review and make them better!

**Comment by wooorm** [comment]
@shanehandley Ping!

**Comment by shanehandley** [comment]
No worries I will give this a crack 👍

**Comment by shanehandley** [comment]
I've added a very basic types to my fork: https://github.com/shanehandley/unist-util-inspect/blob/master/index.d.ts

I'm not proposing to include them in the main repo, it's just so you can check out my fork and test 👍

**Comment by Rokt33r** [comment]
@shanehandley Could you submit a pr from the forked repository? Then, we could review it more easily and give some more direction.

And could you do setting up type testing too?
https://github.com/syntax-tree/unist-builder/pull/3/files
